tab_spaces = 2
color = "Always"
condense_wildcard_suffixes = true
control_brace_style = "ClosingNextLine"
fn_single_line = true
format_code_in_doc_comments = true
format_strings = true
hex_literal_case = "Lower"
imports_layout = "HorizontalVertical"
match_arm_leading_pipes = "Always"
match_block_trailing_comma = true
imports_granularity = "Crate"
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
reorder_imports = true
group_imports = "One"
struct_field_align_threshold = 20
trailing_comma = "Always"
trailing_semicolon = false
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
