array_width = 60
attr_fn_like_width = 70
chain_width = 60
color = "Always"
condense_wildcard_suffixes = true
control_brace_style = "ClosingNextLine"
edition = "2021"
fn_call_width = 60
fn_params_layout = "Compressed"
fn_single_line = true
format_code_in_doc_comments = true
format_strings = true
group_imports = "One"
hard_tabs = false
hex_literal_case = "Lower"
imports_granularity = "Crate"
imports_layout = "HorizontalVertical"
match_arm_leading_pipes = "Always"
match_block_trailing_comma = true
max_width = 80
normalize_comments = true
normalize_doc_attributes = true
remove_nested_parens = true
reorder_impl_items = true
reorder_imports = true
reorder_modules = true
struct_field_align_threshold = 20
struct_lit_width = 18
struct_variant_width = 35
tab_spaces = 2
trailing_comma = "Always"
trailing_semicolon = false
use_field_init_shorthand = true
use_small_heuristics = "Default"
use_try_shorthand = true
wrap_comments = true
